### ISSUE TITLE
Problemas no link de acesso da  página

### ISSUE THREAD

**Issue by Creuma-Kuzola** [EufranioDiogo/static-job-listings#1]
Olá @EufranioDiogo!
 O Link de acesso que disponibilizou para a página está com problemas.
Aconselho-te a verificares o que se passa.

**Comment by EufranioDiogo** [comment]
Obrigado @Creuma-Kuzola pela chamada de atenção e sim já resolvi, é que eu tinha esquecido de colocar on as configurações do github pages. Obrigado

**Comment by Creuma-Kuzola** [comment]
De nada, @EufranioDiogo .
Já consegui acessar a página meus parabéns, está linda!

**Comment by EufranioDiogo** [comment]
Obrigado pela issue @Creuma-Kuzola  e também e obrigado pelo feedback da page :heart:
E estaremos sempre aqui para responder as suas issues e sugestões ;-)
